// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IUuidGenerator is an autogenerated mock type for the IUuidGenerator type
type IUuidGenerator struct {
	mock.Mock
}

type IUuidGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *IUuidGenerator) EXPECT() *IUuidGenerator_Expecter {
	return &IUuidGenerator_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function with no fields
func (_m *IUuidGenerator) Generate() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// IUuidGenerator_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type IUuidGenerator_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
func (_e *IUuidGenerator_Expecter) Generate() *IUuidGenerator_Generate_Call {
	return &IUuidGenerator_Generate_Call{Call: _e.mock.On("Generate")}
}

func (_c *IUuidGenerator_Generate_Call) Run(run func()) *IUuidGenerator_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IUuidGenerator_Generate_Call) Return(_a0 string) *IUuidGenerator_Generate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IUuidGenerator_Generate_Call) RunAndReturn(run func() string) *IUuidGenerator_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// NewIUuidGenerator creates a new instance of IUuidGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIUuidGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *IUuidGenerator {
	mock := &IUuidGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
