// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	"Todo-List/internProject/graphQL_service/graph/model"
	models "Todo-List/internProject/todo_app_service/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// todoConverter is an autogenerated mock type for the todoConverter type
type todoConverter struct {
	mock.Mock
}

type todoConverter_Expecter struct {
	mock *mock.Mock
}

func (_m *todoConverter) EXPECT() *todoConverter_Expecter {
	return &todoConverter_Expecter{mock: &_m.Mock}
}

// ManyToGQL provides a mock function with given fields: todos
func (_m *todoConverter) ManyToGQL(todos []*models.Todo) []*model.Todo {
	ret := _m.Called(todos)

	if len(ret) == 0 {
		panic("no return value specified for ManyToGQL")
	}

	var r0 []*model.Todo
	if rf, ok := ret.Get(0).(func([]*models.Todo) []*model.Todo); ok {
		r0 = rf(todos)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Todo)
		}
	}

	return r0
}

// todoConverter_ManyToGQL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ManyToGQL'
type todoConverter_ManyToGQL_Call struct {
	*mock.Call
}

// ManyToGQL is a helper method to define mock.On call
//   - todos []*models.Todo
func (_e *todoConverter_Expecter) ManyToGQL(todos interface{}) *todoConverter_ManyToGQL_Call {
	return &todoConverter_ManyToGQL_Call{Call: _e.mock.On("ManyToGQL", todos)}
}

func (_c *todoConverter_ManyToGQL_Call) Run(run func(todos []*models.Todo)) *todoConverter_ManyToGQL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]*models.Todo))
	})
	return _c
}

func (_c *todoConverter_ManyToGQL_Call) Return(_a0 []*model.Todo) *todoConverter_ManyToGQL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *todoConverter_ManyToGQL_Call) RunAndReturn(run func([]*models.Todo) []*model.Todo) *todoConverter_ManyToGQL_Call {
	_c.Call.Return(run)
	return _c
}

// ToGQL provides a mock function with given fields: todo
func (_m *todoConverter) ToGQL(todo *models.Todo) *model.Todo {
	ret := _m.Called(todo)

	if len(ret) == 0 {
		panic("no return value specified for ToGQL")
	}

	var r0 *model.Todo
	if rf, ok := ret.Get(0).(func(*models.Todo) *model.Todo); ok {
		r0 = rf(todo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Todo)
		}
	}

	return r0
}

// todoConverter_ToGQL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToGQL'
type todoConverter_ToGQL_Call struct {
	*mock.Call
}

// ToGQL is a helper method to define mock.On call
//   - todo *models.Todo
func (_e *todoConverter_Expecter) ToGQL(todo interface{}) *todoConverter_ToGQL_Call {
	return &todoConverter_ToGQL_Call{Call: _e.mock.On("ToGQL", todo)}
}

func (_c *todoConverter_ToGQL_Call) Run(run func(todo *models.Todo)) *todoConverter_ToGQL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Todo))
	})
	return _c
}

func (_c *todoConverter_ToGQL_Call) Return(_a0 *model.Todo) *todoConverter_ToGQL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *todoConverter_ToGQL_Call) RunAndReturn(run func(*models.Todo) *model.Todo) *todoConverter_ToGQL_Call {
	_c.Call.Return(run)
	return _c
}

// newTodoConverter creates a new instance of todoConverter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newTodoConverter(t interface {
	mock.TestingT
	Cleanup(func())
}) *todoConverter {
	mock := &todoConverter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
