// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	http "net/http"

	io "io"

	mock "github.com/stretchr/testify/mock"
)

// HttpRequester is an autogenerated mock type for the HttpRequester type
type HttpRequester struct {
	mock.Mock
}

type HttpRequester_Expecter struct {
	mock *mock.Mock
}

func (_m *HttpRequester) EXPECT() *HttpRequester_Expecter {
	return &HttpRequester_Expecter{mock: &_m.Mock}
}

// NewRequestWithContext provides a mock function with given fields: ctx, method, url, body
func (_m *HttpRequester) NewRequestWithContext(ctx context.Context, method string, url string, body io.Reader) (*http.Request, error) {
	ret := _m.Called(ctx, method, url, body)

	if len(ret) == 0 {
		panic("no return value specified for NewRequestWithContext")
	}

	var r0 *http.Request
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, io.Reader) (*http.Request, error)); ok {
		return rf(ctx, method, url, body)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, io.Reader) *http.Request); ok {
		r0 = rf(ctx, method, url, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Request)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, io.Reader) error); ok {
		r1 = rf(ctx, method, url, body)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HttpRequester_NewRequestWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewRequestWithContext'
type HttpRequester_NewRequestWithContext_Call struct {
	*mock.Call
}

// NewRequestWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - method string
//   - url string
//   - body io.Reader
func (_e *HttpRequester_Expecter) NewRequestWithContext(ctx interface{}, method interface{}, url interface{}, body interface{}) *HttpRequester_NewRequestWithContext_Call {
	return &HttpRequester_NewRequestWithContext_Call{Call: _e.mock.On("NewRequestWithContext", ctx, method, url, body)}
}

func (_c *HttpRequester_NewRequestWithContext_Call) Run(run func(ctx context.Context, method string, url string, body io.Reader)) *HttpRequester_NewRequestWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(io.Reader))
	})
	return _c
}

func (_c *HttpRequester_NewRequestWithContext_Call) Return(_a0 *http.Request, _a1 error) *HttpRequester_NewRequestWithContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HttpRequester_NewRequestWithContext_Call) RunAndReturn(run func(context.Context, string, string, io.Reader) (*http.Request, error)) *HttpRequester_NewRequestWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// NewHttpRequester creates a new instance of HttpRequester. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHttpRequester(t interface {
	mock.TestingT
	Cleanup(func())
}) *HttpRequester {
	mock := &HttpRequester{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
