// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// RequestAuthSetter is an autogenerated mock type for the RequestAuthSetter type
type RequestAuthSetter struct {
	mock.Mock
}

type RequestAuthSetter_Expecter struct {
	mock *mock.Mock
}

func (_m *RequestAuthSetter) EXPECT() *RequestAuthSetter_Expecter {
	return &RequestAuthSetter_Expecter{mock: &_m.Mock}
}

// DecorateRequest provides a mock function with given fields: ctx, req
func (_m *RequestAuthSetter) DecorateRequest(ctx context.Context, req *http.Request) (*http.Request, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for DecorateRequest")
	}

	var r0 *http.Request
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *http.Request) (*http.Request, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *http.Request) *http.Request); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Request)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *http.Request) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RequestAuthSetter_DecorateRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecorateRequest'
type RequestAuthSetter_DecorateRequest_Call struct {
	*mock.Call
}

// DecorateRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - req *http.Request
func (_e *RequestAuthSetter_Expecter) DecorateRequest(ctx interface{}, req interface{}) *RequestAuthSetter_DecorateRequest_Call {
	return &RequestAuthSetter_DecorateRequest_Call{Call: _e.mock.On("DecorateRequest", ctx, req)}
}

func (_c *RequestAuthSetter_DecorateRequest_Call) Run(run func(ctx context.Context, req *http.Request)) *RequestAuthSetter_DecorateRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*http.Request))
	})
	return _c
}

func (_c *RequestAuthSetter_DecorateRequest_Call) Return(_a0 *http.Request, _a1 error) *RequestAuthSetter_DecorateRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RequestAuthSetter_DecorateRequest_Call) RunAndReturn(run func(context.Context, *http.Request) (*http.Request, error)) *RequestAuthSetter_DecorateRequest_Call {
	_c.Call.Return(run)
	return _c
}

// NewRequestAuthSetter creates a new instance of RequestAuthSetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRequestAuthSetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *RequestAuthSetter {
	mock := &RequestAuthSetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
