// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UuidGenerator is an autogenerated mock type for the uuidGenerator type
type UuidGenerator struct {
	mock.Mock
}

type UuidGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *UuidGenerator) EXPECT() *UuidGenerator_Expecter {
	return &UuidGenerator_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function with no fields
func (_m *UuidGenerator) Generate() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// UuidGenerator_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type UuidGenerator_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
func (_e *UuidGenerator_Expecter) Generate() *UuidGenerator_Generate_Call {
	return &UuidGenerator_Generate_Call{Call: _e.mock.On("Generate")}
}

func (_c *UuidGenerator_Generate_Call) Run(run func()) *UuidGenerator_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UuidGenerator_Generate_Call) Return(_a0 string) *UuidGenerator_Generate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UuidGenerator_Generate_Call) RunAndReturn(run func() string) *UuidGenerator_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// NewUuidGenerator creates a new instance of UuidGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUuidGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *UuidGenerator {
	mock := &UuidGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
