// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	"Todo-List/internProject/graphQL_service/graph/model"
	models "Todo-List/internProject/todo_app_service/pkg/models"

	mock "github.com/stretchr/testify/mock"
)

// TodoConverter is an autogenerated mock type for the todoConverter type
type TodoConverter struct {
	mock.Mock
}

type TodoConverter_Expecter struct {
	mock *mock.Mock
}

func (_m *TodoConverter) EXPECT() *TodoConverter_Expecter {
	return &TodoConverter_Expecter{mock: &_m.Mock}
}

// ManyToGQL provides a mock function with given fields: _a0
func (_m *TodoConverter) ManyToGQL(_a0 []*models.Todo) []*model.Todo {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for ManyToGQL")
	}

	var r0 []*model.Todo
	if rf, ok := ret.Get(0).(func([]*models.Todo) []*model.Todo); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Todo)
		}
	}

	return r0
}

// TodoConverter_ManyToGQL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ManyToGQL'
type TodoConverter_ManyToGQL_Call struct {
	*mock.Call
}

// ManyToGQL is a helper method to define mock.On call
//   - _a0 []*models.Todo
func (_e *TodoConverter_Expecter) ManyToGQL(_a0 interface{}) *TodoConverter_ManyToGQL_Call {
	return &TodoConverter_ManyToGQL_Call{Call: _e.mock.On("ManyToGQL", _a0)}
}

func (_c *TodoConverter_ManyToGQL_Call) Run(run func(_a0 []*models.Todo)) *TodoConverter_ManyToGQL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]*models.Todo))
	})
	return _c
}

func (_c *TodoConverter_ManyToGQL_Call) Return(_a0 []*model.Todo) *TodoConverter_ManyToGQL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TodoConverter_ManyToGQL_Call) RunAndReturn(run func([]*models.Todo) []*model.Todo) *TodoConverter_ManyToGQL_Call {
	_c.Call.Return(run)
	return _c
}

// NewTodoConverter creates a new instance of TodoConverter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTodoConverter(t interface {
	mock.TestingT
	Cleanup(func())
}) *TodoConverter {
	mock := &TodoConverter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
