BEGIN TRANSACTION;

DROP INDEX IF EXISTS idx_lists_owner_id;
DROP INDEX IF EXISTS idx_todos_list_id;

DROP TABLE IF EXISTS user_lists;
DROP TABLE IF EXISTS todos;
DROP TABLE IF EXISTS lists;
DROP TABLE IF EXISTS users;

DROP TYPE IF EXISTS USER_ROLE;
DROP TYPE IF EXISTS STATUS;

COMMIT;