// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// StateGenerator is an autogenerated mock type for the stateGenerator type
type StateGenerator struct {
	mock.Mock
}

type StateGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *StateGenerator) EXPECT() *StateGenerator_Expecter {
	return &StateGenerator_Expecter{mock: &_m.Mock}
}

// GenerateState provides a mock function with no fields
func (_m *StateGenerator) GenerateState() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GenerateState")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StateGenerator_GenerateState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateState'
type StateGenerator_GenerateState_Call struct {
	*mock.Call
}

// GenerateState is a helper method to define mock.On call
func (_e *StateGenerator_Expecter) GenerateState() *StateGenerator_GenerateState_Call {
	return &StateGenerator_GenerateState_Call{Call: _e.mock.On("GenerateState")}
}

func (_c *StateGenerator_GenerateState_Call) Run(run func()) *StateGenerator_GenerateState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *StateGenerator_GenerateState_Call) Return(_a0 string, _a1 error) *StateGenerator_GenerateState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StateGenerator_GenerateState_Call) RunAndReturn(run func() (string, error)) *StateGenerator_GenerateState_Call {
	_c.Call.Return(run)
	return _c
}

// NewStateGenerator creates a new instance of StateGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStateGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *StateGenerator {
	mock := &StateGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
