// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	handler_models "Todo-List/internProject/todo_app_service/pkg/handler_models"
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "Todo-List/internProject/todo_app_service/pkg/models"
)

// JwtIssuer is an autogenerated mock type for the jwtIssuer type
type JwtIssuer struct {
	mock.Mock
}

type JwtIssuer_Expecter struct {
	mock *mock.Mock
}

func (_m *JwtIssuer) EXPECT() *JwtIssuer_Expecter {
	return &JwtIssuer_Expecter{mock: &_m.Mock}
}

// GetRenewedTokens provides a mock function with given fields: _a0, _a1
func (_m *JwtIssuer) GetRenewedTokens(_a0 context.Context, _a1 *handler_models.Refresh) (*models.CallbackResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetRenewedTokens")
	}

	var r0 *models.CallbackResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *handler_models.Refresh) (*models.CallbackResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *handler_models.Refresh) *models.CallbackResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CallbackResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *handler_models.Refresh) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// JwtIssuer_GetRenewedTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRenewedTokens'
type JwtIssuer_GetRenewedTokens_Call struct {
	*mock.Call
}

// GetRenewedTokens is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *handler_models.Refresh
func (_e *JwtIssuer_Expecter) GetRenewedTokens(_a0 interface{}, _a1 interface{}) *JwtIssuer_GetRenewedTokens_Call {
	return &JwtIssuer_GetRenewedTokens_Call{Call: _e.mock.On("GetRenewedTokens", _a0, _a1)}
}

func (_c *JwtIssuer_GetRenewedTokens_Call) Run(run func(_a0 context.Context, _a1 *handler_models.Refresh)) *JwtIssuer_GetRenewedTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*handler_models.Refresh))
	})
	return _c
}

func (_c *JwtIssuer_GetRenewedTokens_Call) Return(_a0 *models.CallbackResponse, _a1 error) *JwtIssuer_GetRenewedTokens_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *JwtIssuer_GetRenewedTokens_Call) RunAndReturn(run func(context.Context, *handler_models.Refresh) (*models.CallbackResponse, error)) *JwtIssuer_GetRenewedTokens_Call {
	_c.Call.Return(run)
	return _c
}

// NewJwtIssuer creates a new instance of JwtIssuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJwtIssuer(t interface {
	mock.TestingT
	Cleanup(func())
}) *JwtIssuer {
	mock := &JwtIssuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
