// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// TimeGenerator is an autogenerated mock type for the timeGenerator type
type TimeGenerator struct {
	mock.Mock
}

type TimeGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *TimeGenerator) EXPECT() *TimeGenerator_Expecter {
	return &TimeGenerator_Expecter{mock: &_m.Mock}
}

// Now provides a mock function with no fields
func (_m *TimeGenerator) Now() time.Time {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Now")
	}

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// TimeGenerator_Now_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Now'
type TimeGenerator_Now_Call struct {
	*mock.Call
}

// Now is a helper method to define mock.On call
func (_e *TimeGenerator_Expecter) Now() *TimeGenerator_Now_Call {
	return &TimeGenerator_Now_Call{Call: _e.mock.On("Now")}
}

func (_c *TimeGenerator_Now_Call) Run(run func()) *TimeGenerator_Now_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TimeGenerator_Now_Call) Return(_a0 time.Time) *TimeGenerator_Now_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TimeGenerator_Now_Call) RunAndReturn(run func() time.Time) *TimeGenerator_Now_Call {
	_c.Call.Return(run)
	return _c
}

// NewTimeGenerator creates a new instance of TimeGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTimeGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *TimeGenerator {
	mock := &TimeGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
