// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// SqlQueryRetriever is an autogenerated mock type for the sqlQueryRetriever type
type SqlQueryRetriever struct {
	mock.Mock
}

type SqlQueryRetriever_Expecter struct {
	mock *mock.Mock
}

func (_m *SqlQueryRetriever) EXPECT() *SqlQueryRetriever_Expecter {
	return &SqlQueryRetriever_Expecter{mock: &_m.Mock}
}

// DetermineCorrectSqlQuery provides a mock function with given fields: ctx
func (_m *SqlQueryRetriever) DetermineCorrectSqlQuery(ctx context.Context) string {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DetermineCorrectSqlQuery")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// SqlQueryRetriever_DetermineCorrectSqlQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DetermineCorrectSqlQuery'
type SqlQueryRetriever_DetermineCorrectSqlQuery_Call struct {
	*mock.Call
}

// DetermineCorrectSqlQuery is a helper method to define mock.On call
//   - ctx context.Context
func (_e *SqlQueryRetriever_Expecter) DetermineCorrectSqlQuery(ctx interface{}) *SqlQueryRetriever_DetermineCorrectSqlQuery_Call {
	return &SqlQueryRetriever_DetermineCorrectSqlQuery_Call{Call: _e.mock.On("DetermineCorrectSqlQuery", ctx)}
}

func (_c *SqlQueryRetriever_DetermineCorrectSqlQuery_Call) Run(run func(ctx context.Context)) *SqlQueryRetriever_DetermineCorrectSqlQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *SqlQueryRetriever_DetermineCorrectSqlQuery_Call) Return(_a0 string) *SqlQueryRetriever_DetermineCorrectSqlQuery_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SqlQueryRetriever_DetermineCorrectSqlQuery_Call) RunAndReturn(run func(context.Context) string) *SqlQueryRetriever_DetermineCorrectSqlQuery_Call {
	_c.Call.Return(run)
	return _c
}

// NewSqlQueryRetriever creates a new instance of SqlQueryRetriever. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSqlQueryRetriever(t interface {
	mock.TestingT
	Cleanup(func())
}) *SqlQueryRetriever {
	mock := &SqlQueryRetriever{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
