// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// JsonService is an autogenerated mock type for the jsonService type
type JsonService struct {
	mock.Mock
}

type JsonService_Expecter struct {
	mock *mock.Mock
}

func (_m *JsonService) EXPECT() *JsonService_Expecter {
	return &JsonService_Expecter{mock: &_m.Mock}
}

// Marshal provides a mock function with given fields: v
func (_m *JsonService) Marshal(v interface{}) ([]byte, error) {
	ret := _m.Called(v)

	if len(ret) == 0 {
		panic("no return value specified for Marshal")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(interface{}) ([]byte, error)); ok {
		return rf(v)
	}
	if rf, ok := ret.Get(0).(func(interface{}) []byte); ok {
		r0 = rf(v)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(v)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// JsonService_Marshal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Marshal'
type JsonService_Marshal_Call struct {
	*mock.Call
}

// Marshal is a helper method to define mock.On call
//   - v interface{}
func (_e *JsonService_Expecter) Marshal(v interface{}) *JsonService_Marshal_Call {
	return &JsonService_Marshal_Call{Call: _e.mock.On("Marshal", v)}
}

func (_c *JsonService_Marshal_Call) Run(run func(v interface{})) *JsonService_Marshal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *JsonService_Marshal_Call) Return(_a0 []byte, _a1 error) *JsonService_Marshal_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *JsonService_Marshal_Call) RunAndReturn(run func(interface{}) ([]byte, error)) *JsonService_Marshal_Call {
	_c.Call.Return(run)
	return _c
}

// NewJsonService creates a new instance of JsonService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJsonService(t interface {
	mock.TestingT
	Cleanup(func())
}) *JsonService {
	mock := &JsonService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
