// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	models "Todo-List/internProject/todo_app_service/pkg/models"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// RandomActivityService is an autogenerated mock type for the randomActivityService type
type RandomActivityService struct {
	mock.Mock
}

type RandomActivityService_Expecter struct {
	mock *mock.Mock
}

func (_m *RandomActivityService) EXPECT() *RandomActivityService_Expecter {
	return &RandomActivityService_Expecter{mock: &_m.Mock}
}

// Suggest provides a mock function with given fields: _a0
func (_m *RandomActivityService) Suggest(_a0 context.Context) (*models.RandomActivity, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Suggest")
	}

	var r0 *models.RandomActivity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*models.RandomActivity, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *models.RandomActivity); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.RandomActivity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RandomActivityService_Suggest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Suggest'
type RandomActivityService_Suggest_Call struct {
	*mock.Call
}

// Suggest is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *RandomActivityService_Expecter) Suggest(_a0 interface{}) *RandomActivityService_Suggest_Call {
	return &RandomActivityService_Suggest_Call{Call: _e.mock.On("Suggest", _a0)}
}

func (_c *RandomActivityService_Suggest_Call) Run(run func(_a0 context.Context)) *RandomActivityService_Suggest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *RandomActivityService_Suggest_Call) Return(_a0 *models.RandomActivity, _a1 error) *RandomActivityService_Suggest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RandomActivityService_Suggest_Call) RunAndReturn(run func(context.Context) (*models.RandomActivity, error)) *RandomActivityService_Suggest_Call {
	_c.Call.Return(run)
	return _c
}

// NewRandomActivityService creates a new instance of RandomActivityService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRandomActivityService(t interface {
	mock.TestingT
	Cleanup(func())
}) *RandomActivityService {
	mock := &RandomActivityService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
